### ISSUE TITLE
WAQ 18

### ISSUE THREAD

**Issue by huguestennier** [tech-conferences/javascript-conferences#122]
Hey, here is a conference that is missing from the list.

```json
  {
    "name": "WAQ18",
    "url": "https://webaquebec.org/",
    "startDate": "2018-04-10",
    "endDate": "2018-04-12",
    "city": "Québec",
    "country": "Canada",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@webaquebec"
  }
```

**Comment by nimzco** [comment]
Just added it, thanks! 👍

**Comment by prigara** [comment]
Hey, thanks for adding a conference! 
Do you mind if we move this conference to the general list? It seems that last year it had very diverse topics from design to marketing but not a lot on JavaScript? Thanks!

**Comment by nimzco** [comment]
Hey @prigara , I took care of it here: https://github.com/tech-conferences/confs.tech/commit/0157ae98c9a7f07b5f4c5eaffa04ffd858bd313b ;)
