### ISSUE TITLE
Web Audio Conf, Berlin

### ISSUE THREAD

**Issue by chrisguttandin** [tech-conferences/javascript-conferences#183]
Hi, I would like to propose adding the Web Audio Conf to the list. It's a conference about all things audio on the web. I think it most likely fits into the "JavaScript" category.

Please let me know if you need more infos.

```json
  {
    "name": "Web Audio Conf",
    "url": "http://webaudioconf.com",
    "startDate": "2018-09-19",
    "endDate": "2018-09-21",
    "city": "Berlin",
    "country": "Germany",
    "cfpUrl": "http://webaudioconf.com/call-for-submissions",
    "cfpEndDate": "2018-04-23",
    "twitter": "@webaudioconf"
  }
```

**Comment by trivikr** [comment]
Thanks @chrisguttandin! 
Added in commit https://github.com/tech-conferences/confs.tech/commit/a624ccbae9c4fe67b438c00fce6c3a4fcd0856b3

**Comment by chrisguttandin** [comment]
Thanks for the quick response, @trivikr.
