### ISSUE TITLE
React Finland

### ISSUE THREAD

**Issue by bebraw** [tech-conferences/javascript-conferences#187]
Hey, here is a conference that is missing from the list.

```json
  {
    "name": "React Finland",
    "url": "https://react-finland.fi/",
    "startDate": "2018-04-24",
    "endDate": "2018-04-26",
    "city": "Helsinki",
    "country": "Finland",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@ReactFinland"
  }
```

**Comment by prigara** [comment]
Hey @bebraw,
Thanks for suggesting the conference, but it is actually already on the list.

**Comment by bebraw** [comment]
Ok. I didn't see it on the site at https://confs.tech/ so I thought it's not in the data.

**Comment by prigara** [comment]
That's weird that it's not shown on the first page, but I see it in the list of JavaScript conferences: https://confs.tech/javascript

@nimzco can you please have a look?

**Comment by nimzco** [comment]
Oh it is weird, because it is here: https://confs.tech/javascript/Finland

I'll check that tonight, good catch, thanks! 👍

**Comment by nimzco** [comment]
This is fixed, Algolia wasn't ordering the results. 👍 Thanks again for the catch!

**Comment by bebraw** [comment]
Perfect. Thanks.
