### ISSUE TITLE
JSConf US 2018

### ISSUE THREAD

**Issue by dlindahl** [tech-conferences/javascript-conferences#191]
Hey, here is a conference that is missing from the list.

```json
  {
    "name": "JSConf US",
    "url": "https://2018.jsconf.us/",
    "startDate": "2018-08-21",
    "endDate": "2018-08-23",
    "city": "Carlsbad, CA",
    "country": "U.S.A.",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@jsconfus"
  }
```

**Comment by nimzco** [comment]
Awesome, I've just added it!
Let us know when the CFP opens 👍

**Comment by dlindahl** [comment]
@nimzco The CFP is now live at https://2018.jsconf.us/call-for-speakers/!

**Comment by trivikr** [comment]
Thanks @dlindahl 
The CFP was added in https://github.com/tech-conferences/javascript-conferences/commit/44bd89198e790778e593ef358ba06f9c0aee8c31
