### ISSUE TITLE
Nordic.js - Stockholm

### ISSUE THREAD

**Issue by kakadiadarpan** [tech-conferences/javascript-conferences#192]
Hey, here is a conference that is missing from the list.

```json
  {
    "name": "Nordic.js",
    "url": "http://nordicjs.com/",
    "startDate": "2018-09-06",
    "endDate": "2018-09-07",
    "city": "Stockholm",
    "country": "Sweden",
    "cfpUrl": "http://cfp.nordicjs.com/",
    "cfpEndDate": "-",
    "twitter": "@nordicjs"
  }
```

**Comment by nimzco** [comment]
Hey there, thanks for the proposal but we have it already: 
https://github.com/tech-conferences/javascript-conferences/blob/master/conferences/2018/javascript.json#L812

**Comment by kakadiadarpan** [comment]
@nimzco My bad, I didn't scroll till the end 😅

**Comment by nimzco** [comment]
No worries! 😄
