### ISSUE TITLE
NConf from Germany (Rostock)

### ISSUE THREAD

**Issue by jnsflint** [tech-conferences/javascript-conferences#96]
Hey, here is a conference that is missing from the list.

```json
  {
    "name": "NConf",
    "url": "https://nconf.de",
    "startDate": "2018-10-23",
    "endDate": "2018-10-23",
    "city": "Rostock",
    "country": "Germany",
    "cfpUrl": "",
    "cfpEndDate": "",
    "facebook": "https://www.facebook.com/NConference/"
  }
```

**Comment by prigara** [comment]
Hi! 
It seems that the conference covers a rather wide range of topics with the main focus on mobile development. Is that right? Would you mind if I move it from the JavaScript category to General?

**Comment by jnsflint** [comment]
Oh yes, you are right, maybe it fits better in General!

**Comment by prigara** [comment]
👍  I've sent a [PR](https://github.com/tech-conferences/confs.tech/pull/60)

**Comment by jnsflint** [comment]
Thanks!
